[build]
  command = "npm run build"
  publish = "dist/client"
  # Base directory where Netlify installs dependencies and runs the build command
  base = "."

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
